# Verify image that was signed with a github attestation
apiVersion: policies.kyverno.io/v1
kind: ImageValidatingPolicy
metadata:
  name: verify-github-attestations
spec:
  validationActions: [Deny]
  webhookConfiguration:
    timeoutSeconds: 15
  failurePolicy: Fail
  matchConstraints:
    resourceRules:
      - apiGroups: [""]
        apiVersions: ["v1"]
        resources: ["pods"]
        operations: ["CREATE", "UPDATE"]
  matchImageReferences:
    - glob: "ghcr.io/lucchmielowski/cosign-testbed:*"
  
  # Define the attestation you want to verify
  attestations:
    - name: slsa
      intoto:
        type: https://slsa.dev/provenance/v1
  
  # Define the attestor (how to verify)
  attestors:
    - name: cosign
      cosign:
        keyless:
          identities:
            - subject: "https://github.com/lucchmielowski/cosign-testbed/.github/workflows/ci.yml@refs/heads/main"
              issuer: "https://token.actions.githubusercontent.com"
        ctlog:
          url: "https://rekor.sigstore.dev"
  
  # Validation expressions
  validations:
  - expression: >-
      images.containers.map(image, 
        verifyAttestationSignatures(image, attestations.slsa, [attestors.cosign])
      ).all(e, e > 0)
    message: "Failed to verify SLSA provenance attestation"
